FROM apache/airflow:2.9.1

USER root
RUN apt-get update && apt-get install -y curl gnupg2 \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev \
    && apt-get clean

USER airflow
RUN pip install --no-cache-dir pyodbc azure-storage-blob python-dotenv dbt-core dbt-sqlserver